[metadata]
name = AMOC Reconstruction
description = Reconstructing the AMOC from Argo based measurements with 
author = Yannick Wölker
long_description = file: README.md
long_description_content_type = text/markdown
license = Apache 2.0
license_file = LICENSE.txt

## These need to be filled in by the author!
# For details see: https://pypi.org/classifiers/

classifiers =
    Development Status ::  2 - Pre-Alpha Copy
    Topic :: Scientific/Engineering
    Intended Audience :: Science/Research
    Operating System :: OS Independent
    Programming Language :: Python
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3.9
    # Dont change this one
    License :: OSI Approved :: Apache License 2.0

## Add your email here
author_email = ywoe@informatik.uni-kiel.de